### ISSUE TITLE
`generateNixPathFromInputs == true && linkInputs == false` should be an error

### ISSUE THREAD

**Issue by lilyball** [gytis-ivaskevicius/flake-utils-plus#106]
If I set `nix.generateNixPathFromInputs = true` it will symlink my inputs into `/etc/nix/inputs` even if I also set `nix.linkInputs = false`. This configuration should be considered an error instead (e.g. using an assertion).

Also, I would suggest that setting `nix.generateNixPathFromInputs = true` should actually change the default value of `nix.linkInputs`, so that way `nixos-option nix.linkInputs` shows the right value.

**Comment by gytis-ivaskevicius** [comment]
Yep, makes sense.
