### ISSUE TITLE
Same condition as previous if expression

### ISSUE THREAD

**Issue by msteen** [gytis-ivaskevicius/flake-utils-plus#109]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/be1be083af014720c14f3b574f57b6173b4915d0/lib/exportModules.nix#L54

Should, I assume, be: `else if (builtins.isAttrs arg) && (!(hasFileAttr arg)) then`

**Comment by blaggacao** [comment]
That is correct! Thank you for spotting this.
