### ISSUE TITLE
`ca-references` in extra-experimental-features is now causing errors

### ISSUE THREAD

**Issue by wahjava** [gytis-ivaskevicius/flake-utils-plus#112]
As per https://github.com/NixOS/nixpkgs/pull/139075#issuecomment-1027772745, there is now an error in `nix.conf` validation, courtesy: https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/lib/mkFlake.nix#L175 . As a workaround one has to disable `nix.conf` configuration check.

Thanks!

**Comment by gytis-ivaskevicius** [comment]
Fixed and pushed to master, thank you!
