### ISSUE TITLE
Deprecated evalModules arguments

### ISSUE THREAD

**Issue by ajgrf** [gytis-ivaskevicius/flake-utils-plus#122]
When I run `nixos-rebuild` I get these warnings:

```
trace: warning: The args argument to evalModules is deprecated. Please set config._module.args instead.
trace: warning: The check argument to evalModules is deprecated. Please set config._module.check instead.
```

I checked nixpkgs and found that the deprecation has already hit [stable](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/lib/modules.nix#L104), so there's probably no reason to wait to fix it.

**Comment by hall** [comment]
Looks like this has already been done in https://github.com/gytis-ivaskevicius/flake-utils-plus/commit/be1be083af014720c14f3b574f57b6173b4915d0 but there hasn't been a release since then.

**Comment by ajgrf** [comment]
Ah, okay! I wouldn't mind seeing a release with that fix, but there's no point to this issue if it's already done.
