### ISSUE TITLE
How to use new flake overlays

### ISSUE THREAD

**Issue by willruggiano** [gytis-ivaskevicius/flake-utils-plus#123]
The new-ish way of defining overlays is like so;
```
{
   overlays.default = final: prev: {...};
}
```

but using overlaysBuilder (seemingly) doesn't make it easy to then use overlays defined this way.

```
channels.nixpkgs.overlaysBuilder = channels: [
  inputs.some-overlay.overlays.default  # doesn't work; no such attribute
];
```

**Comment by willruggiano** [comment]
Hmm. Seems that `overlays.default` is "system agnostic", so simply defining it outside of a `eachDefaultSystem` solves this.

```
eachDefaultSystem (system: { ... }) // {
  overlays.default = ...;
};
```

**Comment by gytis-ivaskevicius** [comment]
Yeah, sorry. Forgot to migrate to the new schema
