### ISSUE TITLE
Need for a `system` arg for outputsBuilder

### ISSUE THREAD

**Issue by anilanar** [gytis-ivaskevicius/flake-utils-plus#129]
If I understood it correctly, `outputsBuilder` is a map fn from system to outputs, but the most crucial information, which system it is, is hidden from it.

Use case:

I want to use `my-flake.stuff.${system}` in `outputsBuilder`.

**Comment by gytis-ivaskevicius** [comment]
Hi, sorry for the late response.  Please use `pkgs.system` for that
