### ISSUE TITLE
extraArgs is marked with a warning in upstream

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#13]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L89

[upstream states](
https://github.com/NixOS/nixpkgs/blob/e7ab6c321919236d5beb51370785d094f6c49a2a/lib/modules.nix#L69-L70):

```nix
{
                , # This would be remove in the future, Prefer _module.args option instead.
                  args ? {}
}
```

at the reasoning of

>
```
/* Evaluate a set of modules.  The result is a set of two
     attributes: ‘options’: the nested set of all option declarations,
     and ‘config’: the nested set of all option values.
     !!! Please think twice before adding to this argument list! The more
     that is specified here instead of in the modules themselves the harder
     it is to transparently move a set of modules to be a submodule of another
     config (as the proper arguments need to be replicated at each call to
     evalModules) and the less declarative the module set is. */
```

It travels via [this nixos waypoint](https://github.com/NixOS/nixpkgs/blob/e7ab6c321919236d5beb51370785d094f6c49a2a/nixos/lib/eval-config.nix#L61).

Unless, I'm misunderstanding something, that is.

**Comment by Pacman99** [comment]
Its also unecessary, it can be just done with `_module.args`. So in flake-utils-plus, you could just add a sharedModule that sets the option instead of using `extraArgs`. A useful feature however is adding `specialArgs` which has to be passed to `nixosSystem`/`evalModules`, and you need specialArgs, if you want to use arguments in `imports` lines.

**Comment by blaggacao** [comment]
#25 implemented this in `staging`.
