### ISSUE TITLE
nixosConfiguration escape hatch

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#14]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L8

It is not entirely clear or self evident why `fup` should provide this service.

Sure, it is nice to have, but it is also only a `// nixosConfigurations` away in the top level flake.

/cc @Pacman99

**Comment by Pacman99** [comment]
It might be for backward compatibility. Also perhaps it could be useful to still get module args(nixpkgs) and other things, but I don't think thats done at the moment.

**Comment by gytis-ivaskevicius** [comment]
Responded with the reasoning of it in the PR itself

**Comment by blaggacao** [comment]
Suggestion in the PR looks like a better fix for this. The main motive was to get this out of the function signature, but it can be passed and `lib.recursiveUpdate`d as a friendly service from `fup` , still via `...`.

**Comment by gytis-ivaskevicius** [comment]
Yeah, maybe you are right

**Comment by blaggacao** [comment]
This has been dealt with in #17 (via deprecation)
