### ISSUE TITLE
Error trying to run `fup-repl`

### ISSUE THREAD

**Issue by Anomalocaridid** [gytis-ivaskevicius/flake-utils-plus#143]
Whenever I try to run `fup-repl` through the `repl` command, I get the following error:
```
Nix 2.21.0
Type :? for help.
error: installable '/nix/store/87c3crz9nsxpi9py3sjd57shla01zqh5-repl.nix' does not correspond to a Nix language value
Try 'nix --help' for more information.
```

In case it matters, I am on NixOS unstable, I have a flake-based setup, and I last updated about two days ago.

**Comment by gytis-ivaskevicius** [comment]
yeah, I have the same issue. Unfortunately I have not investigated just yet and it is very bothering me :sweat_smile: 
I would appreciate it if you could take a look https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/lib/fup-repl.nix otherwise I hope that ill find time soon

**Comment by Anomalocaridid** [comment]
I'd be happy to take a look. It's a relief that I can now rule out my personal setup.

**Comment by gytis-ivaskevicius** [comment]
Fixed in latest release
