### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#16]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L9

`nixosProfiles` do contain system profiles, in a sense, but more accurately they contain host configs.

This clashes with devos' usage of the term `profiles` which is reserved for a very special meaning:

- profiles cannot declare options, but only make use of them. (while anything that declares options are _modules_)
- this rule makes modules a lot more reusable among the community

With `fup` reserving the name, we might have a problem finding an alternative naming scheme. (and also it's somewhat established, already)

/cc @Pacman99

**Comment by nrdxp** [comment]
FWIW, I got the term "profiles" directly from the [nixpkgs module directory](https://github.com/NixOS/nixpkgs/tree/master/nixos/modules/profiles) where it is already being in this fashion.

**Comment by gytis-ivaskevicius** [comment]
I am quite a fan of the name `profiles` for this particular use case and you must suggest quite a bit more attractive naming for this particular case for me to change it.

Also, may I add that I've seen several repos with `profiles` folder which represents the same thing as flake-utils-plus do.

**Comment by blaggacao** [comment]
Hm, @gytis-ivaskevicius that does not solve my problem. Would you care solving it at all?

**Comment by gytis-ivaskevicius** [comment]
Alright, this will be fixed using the name `nixosHosts` as part of the wrapper function for time being until we finalize the API

**Comment by blaggacao** [comment]
Thank you! Much appreciated. :+1:

**Comment by blaggacao** [comment]
closed in #20
