### ISSUE TITLE
appsBuilder

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#3]
What is the point of an `appsBuilder` for system flakes? Is that remeniscent of an analogy with flake-utils or has it a use case, which I'm not aware of / have not explored yet?

**Comment by Pacman99** [comment]
I think its for the literal `apps` output in flakes.

**Comment by gytis-ivaskevicius** [comment]
This project implements "builders" for all arguments that depend on `<system>` https://nixos.wiki/wiki/Flakes#Output_schema 

Values that are passed as`<system>` can be configured using `supportedSystems` argument

TL;DR: It works in a very similar manner that `flake-utils` does
