### ISSUE TITLE
Implement NIX_PATH

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [gytis-ivaskevicius/flake-utils-plus#30]
This is more of a question than an issue.
@blaggacao @Pacman99 - if we were to compare master vs staging branches - currently NIX_PATH implementation does not exist there. (https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/modules/saneFlakeDefaults.nix) 

I am considering re-adding it with nixpkgs definition only. What are your guy's thoughts on it? And how should it be implemented?

Note: I'd like to avoid linking nixpkgs via `environment.etc`

Related: https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/5

**Comment by Pacman99** [comment]
I think there are some conveniences to nix path, like `nix repl "<nixpkgs>"`, that I use. So I think it would be nice.

**Comment by blaggacao** [comment]
I have no opinion, other than I guess we agree, it should go away at some point in the future.

**Comment by gytis-ivaskevicius** [comment]
from my point of view its mostly used for `nix-shell -p` :D 

Also, not sure if you guys noticed but there is a pretty cool nix repl implemented as part of this flake

**Comment by gytis-ivaskevicius** [comment]
Closing due to lack of interest from pretty much everybody

**Comment by noonien** [comment]
If anyone else is wondering, after setting `nix.linkInputs = true;`, setting `nix.            nixPath = [ "/etc/nix/inputs" ];` is enough to make all inputs available to nix. This makes `nix-shell -p` work again, even after updating.
