### ISSUE TITLE
Using nixosSystem from the right channel

### ISSUE THREAD

**Issue by arnarg** [gytis-ivaskevicius/flake-utils-plus#37]
I've been attempting to use `systemFlake` as it cleans up my messy flake. However I have all my laptops on `nixos-unstable` while I have a server on `nixos-20.09` and the server system doesn't build because the unstable uses package `util-linux` somewhere while only `utillinux` exists in `20.09`.

Now I noticed the comment at https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/systemFlake.nix#L62. What is the reasoning this isn't possible?

It would fill my need perfectly if this would become possible.

Thanks for this project.

**Comment by Pacman99** [comment]
This is fixed in the staging branch. I think it was hard to get the nixosSystem for the channel that was set. But it was fixed recently by using channelName to pull the right nixosSystem by default - you can also now customize the builder that is passed.
It should work in the next release.

**Comment by arnarg** [comment]
Oh perfect! Thanks!
