### ISSUE TITLE
nixUnstable -> nixFlakes

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#60]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/e7ae270a23695b50fbb6b72759a7fb1e3340ca86/systemFlake.nix#L141

Now, there is https://github.com/NixOS/nixpkgs/pull/120141.

We need to wait and observer a little, but let's backlog this for consideration.

**Comment by gytis-ivaskevicius** [comment]
I do indeed like that!! Patch seems to be nice and simple so I'd think that there is no need to even wait for anything?

**Comment by gytis-ivaskevicius** [comment]
Resolved in staging
