### ISSUE TITLE
`channels.<name>.input` should be auto picked up if not explicitly defined

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [gytis-ivaskevicius/flake-utils-plus#61]
Just a simplification for a very common use case. Should not be complicated to implement

https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/staging/src/systemFlake.nix#L182-L193

**Comment by Pacman99** [comment]
Ohh yeah we set this up in devos, should be simple enough to implement here.

Maybe we can add a `evalChannelArgs` to be able to set defaults for channel arguments, "channel submodule".

**Comment by gytis-ivaskevicius** [comment]
@Pacman99 mind giving me some sort of example of this `evalChannelArgs`?

**Comment by Pacman99** [comment]
```nix
evalChannelArgs = name:
  { input ? inputs.name
  , overlaysBuilder ? (_: [ ])
  , config ? { }
```
just a random idea, not sure if it should be done.

**Comment by gytis-ivaskevicius** [comment]
Oh, I get it. But I don't think it brings much if any value? So I'm thinking that this should get implemented when some sort of use case comes up

**Comment by gytis-ivaskevicius** [comment]
Resolved in staging
