### ISSUE TITLE
Feature request: implement a'la nixos-generators functionality

### ISSUE THREAD

**Issue by Unrooted** [gytis-ivaskevicius/flake-utils-plus#7]
Making an .iso file (or any other format) out of currently running system can be helpful. 
Especially in case where one wants to use it as on-the-go system and carry their configs and apps everywhere with them. Useful thing when you're forced to work not on your hardware. 
Currently, seems like there is such way to do so with [nixos-generators](https://github.com/nix-community/nixos-generators). It would be great to integrate such features to your project as well, instead of rewriting flake.nix just for the sake of having an .iso from current system.

**Comment by blaggacao** [comment]
https://github.com/divnix/devos/blob/01b05551175ba103ea8e2c7682916003ded73f8d/lib/devos/devosSystem.nix#L12-L78

**Comment by blaggacao** [comment]
I guess we might need some sort of interface into https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L63

**Comment by blaggacao** [comment]
`// optional configurationsBuilder { packages = configurationsBuilder pkgs; }` ?!?

**Comment by blaggacao** [comment]
This is now possible in principle (and largely untested in the wilde) through #17.

@Unrooted Would you want to consider closing this?

**Comment by Unrooted** [comment]
Sure, thanks for help!
