### ISSUE TITLE
repl depending on flake is incompatible with registry-less quick-nix-registry

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#75]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/5f0106ff765774de60295c0e011363be7bb7b81e/lib/repl.nix#L5

probably confilcts with https://github.com/divnix/quick-nix-registry/blob/e566b3d61ba91f8d797d309cf2a93b3c0ce9df5e/flake.nix#L27

I don't know if this actually manifests, but it looks like things are crossing at the wrong angle, here...

I'd have to think more about it, but wanted to kick-off a discussion while these changes are still fresh.

/cc @nrdxp

**Comment by nrdxp** [comment]
Probably an mkForce quick-nix should be enough to resolve no?

**Comment by gytis-ivaskevicius** [comment]
This is repl only. As long as devos does not use it - it's fine. There is nothing to `mkForce`. I do not get whats the issue here

**Comment by blaggacao** [comment]
> I'd have to think more about it, but wanted to kick-off a discussion while these changes are still fresh.

Up to now, it's my gut talking (who is probably the better programmer between the two of us). Something does not feel right. I plan to implement devos' `flk` with a registry-less reference to self.

> I do not get whats the issue here

Once I've completed the above, I might be in a better position to respond accurately. :smile:

**Comment by gytis-ivaskevicius** [comment]
Any update on this?

**Comment by blaggacao** [comment]
I think this is resolved downstream with `divnix/bud`. I'm not (yet) sure if it's worth asking for a separate activation flag for the `self` in the registry. But I think if that comes up again in my research, I'll open a new issue.
