### ISSUE TITLE
The default for `experimental-features` is not fully enabling CA

### ISSUE THREAD

**Issue by NobbZ** [gytis-ivaskevicius/flake-utils-plus#77]
The current default for `experimental-features` enables `ca-derivations`, which enables one to **build** content addressed derivations, but not to have them as inputs to other derivations, regardless of them beeing CA or IA.

Therefore please also enable `ca-references` by default.

**Comment by blaggacao** [comment]
> Therefore please also enable ca-references by default.

I'd rather argue for removing anything non-flake related. Other feature flags are orthogonal to this entire repo and people would be rightfully surprised to find them set here.

**Comment by NobbZ** [comment]
As CA was enabled, I assumed, its actually required for FU+. If this is not the case, I am the same opinion as David, please remove it completely and make it easier for users to add experimental features as suggested in #76.
