### ISSUE TITLE
Importers

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#8]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/flake.nix#L29-L35

This is effectively an implementation of an importer and it is of undisputed handy nature.
Are other (generic!) [importers](https://github.com/blaggacao/devos/blob/5d80663bcd3f65cc95fd965b49becc7b24ebf9d4/lib/devos/importer.nix) potentially in scope?

/cc @Pacman99

**Comment by blaggacao** [comment]
Importers work best with an elaborate implementation within the nix module system for doc, type checking, preprocessing, etc. To maintain this repo `nixpkgs`-dep free, we figured it would be best to leave that to the `devos` sister project, which does not have this restriction (on nixpkgs-freeness).

**Comment by gytis-ivaskevicius** [comment]
At some point ill look over the importers devos has, might be cool to add some. Till this day I am not exactly sure about all the terms and use-cases so it's going to take me a little bit to figure out if it makes sense to have it as part of fup or not.

Also, this implementation seems to cover most cases https://github.com/gytis-ivaskevicius/nixfiles/blob/master/flake.nix#L47 (According to DevOS terms one would call it "Profiles"? )

**Comment by blaggacao** [comment]
The (one) fundamental concept of devos is to make a clear distinction between modules that implement specifications and profiles that apply them.

Defining only a module would never alter the system state by itself, without also applying it in a profile.

That enhances the sharing model where modules remain sharable independently of their activation.

Suites are a way to group profiles into broader useful categories that, complememted with hardware specific stuff, make a host config.
