### ISSUE TITLE
Problem building emacs with external package

### ISSUE THREAD

**Issue by codygman** [gytis-ivaskevicius/flake-utils-plus#80]
I originally had this issue in divnix/devos#339 and thought perhaps I could avoid it with flake-utils-plus since there are less layers of abstraction.

However, it appears that flake utils plus also has the issue or the problem has been me making some mistake all along :sweat_smile: 

Here was [my attempt to add emacs with that external package](https://github.com/codygman/dotfiles-1/commit/3c1b6da90e13bb2d49728eb8f0d80d5d292cc260). Note that you can reproduce by trying to build that repo at that commit.

**Comment by gytis-ivaskevicius** [comment]
Closing since I believe this is fixed

**Comment by codygman** [comment]
Thanks, I'll try this out soon!
