### ISSUE TITLE
config generator (nixos)

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#9]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L63

As stated here https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/7#issuecomment-814408863, we need an interface to be able to extend `lib.nixosSystem`while retatining the environment (pkgs, hostname, extraArgs, etc) from the `genericConfigurationsBuilder`.

It looks like
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L8
would not preserve the desired `genericConfigurationsBuilder` environment.

Provides ability to solve #7 downstream.

/cc @Pacman99

**Comment by blaggacao** [comment]
Let `extraModules` be custom modules, then we need a full system evaluation with and without `extraModules` and compare them.

It does not seem like that is something to be achievable via pure module system.

**Comment by Pacman99** [comment]
Doing this within the module system would be very interesting. You would have to pass all modules as a specialArg - I think module arg would work for this too however. And then get access to `nixosSystem` within the module system. I'll try and play around with it and see if how it would work.

**Comment by blaggacao** [comment]
#17 implemented this in `staging`.
