### ISSUE TITLE
Make nixosSystems overridable

### ISSUE THREAD

**Issue by legendofmiracles** [gytis-ivaskevicius/flake-utils-plus#94]
Needed for this: https://github.com/nix-community/nixos-generators/issues/110
And can serve as a temporary workaround for this: https://github.com/NixOS/nixpkgs/pull/101475

**Comment by gytis-ivaskevicius** [comment]
Not sure what is the exact expected result but do you mean this?
```nix
  hosts.<hostname>.builder = args: nix-darwin.lib.darwinSystem (removeAttrs args [ "system" ]);
```

**Comment by fufexan** [comment]
Probably yes, told him the same thing on discord.

**Comment by legendofmiracles** [comment]
> Not sure what is the exact expected result but do you mean this?
> 
> ```nix
>   hosts.<hostname>.builder = args: nix-darwin.lib.darwinSystem (removeAttrs args [ "system" ]);
> ```

I tried using `builder = nixpkgs.lib.makeOverridable nixpkgs.lib.nixosSystem;` as fufexan pointed out, but no dice. Any clue what I'm doing wrong? Must it be a function?

**Comment by legendofmiracles** [comment]
nvm i was being dumb, the line from fufexan solved it, thank you!
